# Generated by Django 5.2.1 on 2025-05-12 22:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('business_name', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='RUT/ID Fiscal')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Región/Estado')),
                ('country', models.CharField(default='Chile', max_length=100, verbose_name='País')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#007bff', help_text='Código hexadecimal del color, ej: #007bff', max_length=7, verbose_name='Color Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('max_users', models.PositiveIntegerField(default=5, verbose_name='Máximo de Usuarios')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name='Fin de Suscripción')),
                ('module_inventory', models.BooleanField(default=True, verbose_name='Módulo Inventario')),
                ('module_sales', models.BooleanField(default=True, verbose_name='Módulo Ventas')),
                ('module_purchases', models.BooleanField(default=True, verbose_name='Módulo Compras')),
                ('module_accounting', models.BooleanField(default=False, verbose_name='Módulo Contabilidad')),
                ('module_crm', models.BooleanField(default=False, verbose_name='Módulo CRM')),
                ('module_hrm', models.BooleanField(default=False, verbose_name='Módulo RRHH')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Imagen de Perfil')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP último acceso')),
                ('language_preference', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=10, verbose_name='Idioma Preferido')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='system.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
