# Generated by Django 5.2.1 on 2025-05-13 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='system.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Código de Barras')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Costo')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Venta')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Actual')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock Mínimo')),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Stock Máximo')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Categoría')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='system.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
                'unique_together': {('company', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3, verbose_name='Tipo')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venta'), ('RETURN', 'Devolución'), ('ADJUSTMENT', 'Ajuste de Inventario'), ('TRANSFER', 'Transferencia'), ('OTHER', 'Otro')], default='OTHER', max_length=20, verbose_name='Motivo')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_movements', to='system.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Producto',
                'verbose_name_plural': 'Movimientos de Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
